import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryProvider } from "@/providers/query-provider";
import { StoreProvider } from "@/providers/store-provider";

import "@/app/globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// const [meResponse] = await Promise.all([
//   tryCatch(authServerActions.getMe()),
// ]);

// if (meResponse.error) {
//   console.error(meResponse.error);
//   return redirect('/auth/login');
// }

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<StoreProvider>
					<QueryProvider>
						{children}
						<Toaster richColors />
					</QueryProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
